DROP TABLE USERS_SNS;
-- 제약 조건과 함께 삭제(제약 조건이 있어도 삭제됨, 권장하지 않음.)
DROP TABLE USERS_SNS CASCADE CONSTRAINTS; 

CREATE TABLE users_sns (
  sns_no       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider     VARCHAR2(50) NOT NULL,
  provider_no  VARCHAR2(255) NOT NULL,
  user_no      NUMBER(10) NOT NULL,
  created_at   DATE DEFAULT SYSDATE,

  CONSTRAINT fk_users_sns_user_no FOREIGN KEY (user_no)
    REFERENCES users(user_no)
    ON DELETE CASCADE
);
COMMENT ON TABLE users_sns is 'SNS 회원';
COMMENT ON COLUMN users_sns.sns_no is 'SNS 회원번호';
COMMENT ON COLUMN users_sns.user_no is '회원번호';
COMMENT ON COLUMN users_sns.provider is 'SNS제공자';
COMMENT ON COLUMN users_sns.provider_no is 'SNS 계정 고유 식별자';

DROP SEQUENCE USERS_SNS_SEQ;

CREATE SEQUENCE USERS_SNS_SEQ
START WITH 1         -- 시작 번호
INCREMENT BY 1       -- 증가값
MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(20) 대응
CACHE 2              -- 2번은 메모리에서만 계산
NOCYCLE;             -- 다시 1부터 생성되는 것을 방지

commit;

